repository:
  name: dev-friends-stater
  description: Node Application
  topics: node
  private: true

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true

  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

teams:
  - name: admin
    permission: admin
  - name: employees
    permission: push

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: ["commitlint"]
      enforce_admins: true
      required_linear_history: false
      required_signatures: true
      required_conversation_resolution: true
      restrictions: null